server:
  port: 8300
  context-path: /scheduling

spring:
  application:
    name: scheduling
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.105:3306/chishenme?characterEncoding=utf-8
    username: root
    password: root